// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNWByek1wtsHlXfvx0epXk2-gIqlniJao',
    appId: '1:307818569339:web:7534384025115597784cde',
    messagingSenderId: '307818569339',
    projectId: 'daafua-ashesi-social',
    authDomain: 'daafua-ashesi-social.firebaseapp.com',
    storageBucket: 'daafua-ashesi-social.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnDh8USCT43WXXGwLtcBiNPsxExvkbp7Q',
    appId: '1:307818569339:android:7c8cd2d7c15e191c784cde',
    messagingSenderId: '307818569339',
    projectId: 'daafua-ashesi-social',
    storageBucket: 'daafua-ashesi-social.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ2oTT_ozRjWu9VjNQW7LTWuTKYPoLQ1A',
    appId: '1:307818569339:ios:7a9da56c9d22054c784cde',
    messagingSenderId: '307818569339',
    projectId: 'daafua-ashesi-social',
    storageBucket: 'daafua-ashesi-social.appspot.com',
    iosClientId: '307818569339-hmcn4e7n2i9npkej8mbsa3slcjnlbsen.apps.googleusercontent.com',
    iosBundleId: 'com.example.ashesiSocial',
  );
}
